create table 
--Apartment details (32)- Atharva
--lease, payment and booking (37) - Sannidhi
--User details, user login, contractor, management and maintenance (37) - Kshitija
--Tenant, Notification, complaint and laundry (35) - Shabana
--Total : 141 columns

#####KSHITIJA

USER_DETAILS
CREATE TABLE USER_DETAILS(
usid NUMBER(3) PRIMARY KEY,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
contact_no NUMBER(10) NOT NULL,
email VARCHAR(255) NOT NULL,
address_line1 VARCHAR(255) NOT NULL,
address_line2 VARCHAR(255) NOT NULL,
city VARCHAR(100) NOT NULL,
zipcode NUMBER(6) NOT NULL,
residence_state VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL,
dob DATE NOT NULL,
sex VARCHAR(10) NOT NULL,
user_type char(1) NOT NULL,
last_login date NOT NULL
)

CREATE TABLE USER_LOGIN(
USERNAME VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
USID NUMBER NOT NULL,
FOREIGN KEY (USID) REFERENCES USER_DETAILS(USID)
)

CREATE TABLE MANAGEMENT_DETAILS(
MGID NUMBER NOT NULL PRIMARY KEY,
M_COMPANY_NAME VARCHAR(255) NOT NULL,
M_REGISTRATION_STATUS CHAR(1) NOT NULL,
M_DATE_CREATED DATE NOT NULL
)


CREATE TABLE CONTRACTOR_DETAILS(
CO_ID NUMBER NOT NULL PRIMARY KEY,
STAFF_ROLE VARCHAR(255) NOT NULL,
CO_SPECIALITY VARCHAR(255) NOT NULL,
CO_HOURS NUMBER NOT NULL,
CO_RATE NUMBER NOT NULL,
CO_EMP_START_DATE DATE NOT NULL,
CO_EMP_END_DATE DATE NOT NULL,
MGID NUMBER NOT NULL,
FOREIGN KEY (MGID) REFERENCES MANAGEMENT_DETAILS(MGID)
)

CREATE TABLE MAINTENANCE_DETAILS(
MT_ID NUMBER NOT NULL PRIMARY KEY,
MAINTENANCE_TYPE VARCHAR(255) NOT NULL,
MAINTENANCE_COMMENTS VARCHAR(255) NOT NULL,
FREQUENCY NUMBER NOT NULL,
DATE_LAST_DONE DATE NOT NULL,
COMPLIANCE_STATUS CHAR(1)NOT NULL,
MGID NUMBER NOT NULL,
FOREIGN KEY (MGID) REFERENCES MANAGEMENT_DETAILS(MGID)
)

########


###################################  SHABANA  ##########################################

CREATE TABLE TENANT_DETAILS(
tid NUMBER NOT NULL PRIMARY KEY,
lid NUMBER NOT NULL,
id_proof_submitted CHAR(1) NOT NULL,
id_proof_document_type VARCHAR(255) NOT NULL
);

CREATE TABLE NOTIFICATION(
nid NUMBER NOT NULL PRIMARY KEY,
notification_type VARCHAR(255) NOT NULL,
notification_comments VARCHAR(255) NOT NULL,
notification_date DATE NOT NULL,
FOREIGN KEY (mgid) REFERENCES MANAGEMENT_DETAILS(mgid),
FOREIGN KEY (tid) REFERENCES TENANT_DETAILS(tid)
);


CREATE TABLE COMPLAINT_DETAILS(
cdid Number NOT NULL PRIMARY KEY,
c_ref_no Number NOT NULL,
c_raised_by_name varchar(255) NOT NULL,
c_raised_by_apt Number NOT NULL,
c_raised_time Number NOT NULL,
c_raised_date date NOT NULL,
c_category varchar(255) NOT NULL,
c_severity varchar(255) NOT NULL,
c_description varchar(255) NOT NULL,
c_status char(1) NOT NULL,
c_closure_date date NOT NULL,
FOREIGN KEY (co_id) REFERENCES CONTRACTOR_DETAILS(co_id),
FOREIGN KEY (nid) REFERENCES NOTIFICATION(nid)
);


CREATE TABLE LAUNDRY_DETAILS(
la_id NUMBER NOT NULL PRIMARY KEY,
la_machine_no Number NOT NULL,
la_washing_load varchar(255) NOT NULL,
la_drying_load varchar(255) NOT NULL,
la_time_started date NOT NULL,
la_time_ended date NOT NULL,
la_status char(1) NOT NULL,
la_fee_washing Number NOT NULL,
la_fee_drying Number NOT NULL,
la_payment_received char(1) NOT NULL,
FOREIGN KEY (nid) REFERENCES NOTIFICATION (nid)
);

#########################################################################

