
SET SERVEROUTPUT ON;
DECLARE



BEGIN



EXECUTE IMMEDIATE'CREATE ROLE TENANT';
EXECUTE IMMEDIATE'GRANT CREATE SESSION, CONNECT TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT ON APARTMENT_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT ON MANAGEMENT_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT ON LEASE_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON TENANT_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON LAUNDRY_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE ON PAYMENT_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE ON COMPLAINT_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT ON MAINTENANCE_DETAILS TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT ON NOTIFICATION TO TENANT';
EXECUTE IMMEDIATE'GRANT SELECT ON VIEW_TENANT TO TENANT';



EXECUTE IMMEDIATE'CREATE ROLE MANAGEMENT';
EXECUTE IMMEDIATE'GRANT CREATE SESSION, CONNECT TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON MANAGEMENT_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON BOOKING TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON APARTMENT_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON TENANT_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON LEASE_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON CONTRACTOR_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON LAUNDRY_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON PAYMENT_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON COMPLAINT_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON MAINTENANCE_DETAILS TO MANAGEMENT';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON NOTIFICATION TO MANAGEMENT';
EXECUTE IMMEDIATE 'GRANT EXECUTE ON MGMT_ADD_NEW_APTS TO MANAGEMENT';
EXECUTE IMMEDIATE 'CREATE OR REPLACE PUBLIC SYNONYM MGMT_ADD_NEW_APTS for appartment_admin.MGMT_ADD_NEW_APTS';








EXECUTE IMMEDIATE'CREATE ROLE CONTRACTOR';
EXECUTE IMMEDIATE'GRANT CREATE SESSION, CONNECT TO CONTRACTOR';
EXECUTE IMMEDIATE'GRANT SELECT ON MANAGEMENT_DETAILS TO CONTRACTOR';
EXECUTE IMMEDIATE'GRANT SELECT ON APARTMENT_DETAILS TO CONTRACTOR';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON CONTRACTOR_DETAILS TO CONTRACTOR';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON COMPLAINT_DETAILS TO CONTRACTOR';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON MAINTENANCE_DETAILS TO CONTRACTOR';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE ON NOTIFICATION TO CONTRACTOR';
EXECUTE IMMEDIATE'GRANT SELECT ON VIEW_CONTRACTOR TO CONTRACTOR';

EXECUTE IMMEDIATE'CREATE ROLE R_USER';
EXECUTE IMMEDIATE'GRANT CREATE SESSION, CONNECT TO R_USER';
EXECUTE IMMEDIATE'GRANT SELECT ON MANAGEMENT_DETAILS TO R_USER';
EXECUTE IMMEDIATE'GRANT SELECT,UPDATE,DELETE ON BOOKING TO R_USER';
EXECUTE IMMEDIATE'GRANT SELECT ON APARTMENT_DETAILS TO R_USER';
EXECUTE IMMEDIATE'GRANT SELECT ON TENANT_DETAILS TO R_USER';
EXECUTE IMMEDIATE'GRANT SELECT ON LEASE_DETAILS TO R_USER';
EXECUTE IMMEDIATE'GRANT SELECT ON VIEW_USER TO R_USER';
EXECUTE IMMEDIATE 'GRANT EXECUTE ON BOOKAPTS TO R_USER';
EXECUTE IMMEDIATE 'CREATE OR REPLACE PUBLIC SYNONYM BOOKAPTS for appartment_admin.BOOKAPTS';
EXECUTE IMMEDIATE 'GRANT EXECUTE ON CANCEL_APTS_BKNG TO R_USER';
EXECUTE IMMEDIATE 'CREATE OR REPLACE PUBLIC SYNONYM CANCEL_APTS_BKNG for appartment_admin.CANCEL_APTS_BKNG';

COMMIT;
END;
