--CREATE USER SANNI IDENTIFIED BY INFODMDD123$;
GRANT TENANT TO SANNI;
--CREATE USER SHABANA IDENTIFIED BY INFODMDD123$;
GRANT MANAGEMENT TO SHABANA;
--CREATE USER ATHARVA IDENTIFIED BY INFODMDD123$;
GRANT R_USER TO ATHARVA;
--CREATE USER KSHITIJA IDENTIFIED BY INFODMDD123$;
GRANT CONTRACTOR TO KSHITIJA;
